services:
  backend:
    build:
      context: ./backend
      platforms:
        - linux/arm64
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3000:3000
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - PORT=3000

  frontend:
    build: 
      context: ./frontend
      platforms:
        - linux/arm64
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80" 
    networks:
      - app_network
    environment:
      - VITE_BACKEND_URL=/

networks:
  app_network:
    driver: bridge