version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3000:3000
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - PORT=3000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80" 
    networks:
      - app_network
    environment:
      - VITE_BACKEND_URL=http://backend:3000

networks:
  app_network:
    driver: bridge